# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: C# bot

on:
  push:
    branches: [ "main", "debug-workflow" ]
    paths: ["**.cs", ".github/workflows/bot.yml"]
  pull_request:
    branches: [ "main" ]
    paths: ["**.cs", ".github/workflows/bot.yml"]

defaults:
 run:
  working-directory: ./Bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload program
      uses: actions/upload-artifact@v3
      with:
        name: Bot
        path: |
          README.md